import psycopg2

def setup_database():
    # Desmembrando a string de conexão para evitar erro com o caractere @ na senha
    db_config = {
        "dbname": "postgres",
        "user": "postgres",
        "password": "J6t2hybt26@",
        "host": "db.bgijgonngrgnvffagsnd.supabase.co",
        "port": "5432"
    }
    
    sql_commands = [
        """
        CREATE TABLE IF NOT EXISTS planos_gerados (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            professor text NOT NULL,
            escola text,
            turma text,
            componente text,
            bimestre int,
            semana int,
            filename text,
            data_geracao timestamptz DEFAULT now(),
            tamanho_kb float
        );
        """,
        "ALTER TABLE planos_gerados ENABLE ROW LEVEL SECURITY;",
        "CREATE POLICY \"Acesso Publico 2\" ON planos_gerados FOR ALL USING (true) WITH CHECK (true);"
    ]

    try:
        print("Conectando ao banco de dados Supabase...")
        conn = psycopg2.connect(**db_config)
        cur = conn.cursor()
        
        for cmd in sql_commands:
            try:
                cur.execute(cmd)
                print(f"Executado com sucesso: {cmd.strip().splitlines()[0][:50]}...")
            except Exception as e:
                print(f"Aviso em comando: {e}")
                conn.rollback()
                continue
        
        conn.commit()
        cur.close()
        conn.close()
        print("\n✅ TUDO PRONTO! A tabela foi criada e configurada com sucesso.")
        
    except Exception as e:
        print(f"❌ Erro fatal ao conectar: {e}")

if __name__ == "__main__":
    setup_database()
